<?php

namespace MovieBundle\Repository;

/**
 * ActeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeursRepository extends \Doctrine\ORM\EntityRepository
{
}
