<?php

namespace MovieBundle\Repository;

/**
 * AdministrateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrateursRepository extends \Doctrine\ORM\EntityRepository
{
}
