<?php

namespace MovieBundle\Repository;

/**
 * ModerateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModerateursRepository extends \Doctrine\ORM\EntityRepository
{
}
