<?php

namespace MovieBundle\Repository;

/**
 * RealisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisateursRepository extends \Doctrine\ORM\EntityRepository
{
}
