<?php

namespace MovieBundle\Repository;

/**
 * SaisonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findSaisons($serie)
	{
		$qb = $this->createQueryBuilder('a')
			->leftJoin('a.series', 'series')
			->addSelect('series');
		$qb
	    ->where('a.series = :id')
	    ->setParameter(":id", $serie);
	    //->orderBy('a.dateAjout', 'DESC');

		return $qb
	    ->getQuery()
	    ->getResult();
	}
}
