<?php

namespace MovieBundle\Repository;

/**
 * ScenaristesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenaristesRepository extends \Doctrine\ORM\EntityRepository
{
}
