<?php

namespace MovieBundle\Repository;

/**
 * SeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll() // récupère et affiche les séries dont les champs "validation" sont à 1
	{
	  $qb = $this->createQueryBuilder('a');

	  $qb
	    ->where('a.validation = 1');
	  $qb
	    ->orderBy('a.nomSerie', 'ASC');

	  return $qb
	    ->getQuery()
	    ->getResult();
	}

	public function selectLast($serie) // sélectionne la série non modifiée pendant qu'elle est en cours de validation
	{
	  $qb = $this->createQueryBuilder('a');

	    $qb
	    ->where('a.nomSerie = :nomSerie')
	    ->setParameter(":nomSerie", $serie)
	    ->orderBy('a.dateAjout', 'ASC')
	    ->setMaxResults('1');

	  return $qb
	    ->getQuery()
	    ->getResult();
	}

	public function findName($serie)
	{
		$qb = $this->createQueryBuilder('a');

	    $qb
	    ->where('a.nomSerie = :nomSerie')
	    ->setParameter(":nomSerie", $serie);

	  return $qb
	    ->getQuery()
	    ->getResult();
	}

	// public function getLastNomSerie() // récupère et affiche les le dernier nom de la série
	// {
	//   $qb = $this->createQueryBuilder('a');

	//   $qb
	//     ->where('a.dateAjout = 1');
	//   $qb
	//     ->orderBy('a.nomSerie', 'ASC');

	//   return $qb
	//     ->getQuery()
	//     ->getResult();
	// }

	public function findAll()
	{
	  $qb = $this->createQueryBuilder('a');

	  $qb
	    ->orderBy('a.validation', 'ASC');
	  

	  return $qb
	    ->getQuery()
	    ->getResult();
	}

	public function getAllHide() // récupère et affiche les séries dont les champs "validation" sont à 0 (pour les modos)
	{
	  $qb = $this->createQueryBuilder('a');

	  $qb
	    ->where('a.validation = 0');

	  return $qb
	    ->getQuery()
	    ->getResult();
	}
}
