<?php

namespace MovieBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll() // récupère et affiche les séries dont les champs "validation" sont à 1
	{
	  $qb = $this->createQueryBuilder('a');

	  $qb
	    ->where('a.id = 3');

	  return $qb
	    ->getQuery()
	    ->getResult();
	}

}
